### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by idkjs** [johnridesabike/react-99#1]
Thanks for sharing this project, sir. Will you add a complete unrelated section on how you generated your docs?

**Comment by johnridesabike** [comment]
I can, although the method I used isn't very elegant. The docs are hand-written in the `/src/example/` directory. The `/docs/` directory is generated with webpack. I had to tweak the ReasonReact template's webpack config to make it work.

I'm hesitant to document the process just because it's hacky and I don't want to implicitly recommend that other people use it.

You can browse `/src/example` and `webpack.config.js` to see exactly what's happening.

**Comment by idkjs** [comment]
Thank you, sir.
